### ISSUE TITLE
Uses nonexistent function `seq-mapn`

### ISSUE THREAD

**Issue by purcell** [Malabarba/beacon#33]
This function does not exist in my fairly recent Emacs snapshot, and therefore makes `beacon` throw errors.

**Comment by Malabarba** [comment]
I added it myself to Emacs, so I guess those snapshots just haven't kept up yet. 😕
You could probably solve this by  installing seq from Melpa, as the Melpa version also has this function (and its version is high enough to take precedence over emacs' built-in).

**Comment by Malabarba** [comment]
Nevermind. I've defined it explicitly for the moment. 
Are you pulling from master or downloading some form of snapshot release? And if it's the latter, which one?

**Comment by purcell** [comment]
It was a MELPA package of beacon. If the code requires upstream features not yet available in Emacs core, then you should depend on a corresponding Emacs version, or a sufficiently high version of `seq` in this case which would force installation of the standalone `seq` package.

**Comment by Malabarba** [comment]
Actually, when I asked whether you were pulling from master, I meant Emacs itself, not beacon. :-)

And yes, that's what I do. 
Beacon depends on seq 1.11, which has this function and is available on the repos. 
The problem is that the seq package on emacs core is labeled with 2.x, so if you're following emacs snapshots then package.el will never install seq from the repos. 

Of course, the seq package on most recent emacs core also has this function, but if your snapshot is a little outdated then you might not have it yet. 

By the way, does the current fix work for you?

**Comment by purcell** [comment]
Aha. Yes, it's a master build of Emacs, and the fix works for me. Same dependency story as with `cl-lib`, I guess: snapshot users can expect occasional breakage if package authors are targeting bleeding-edge APIs.
