### ISSUE TITLE
Occasionally getting "Error running timer ‘beacon--dec’: (end-of-buffer)"

### ISSUE THREAD

**Issue by dakrone** [Malabarba/beacon#42]
I usually get this when I have beacon enabled and use `eww` to open a web page that takes a while to load.

**Comment by Malabarba** [comment]
Yes, I've had this error too in other situations. Sadly, I'm still trying to figure out where/when it happens.

**Comment by otijhuis** [comment]
It happens consistently when using `undo-tree-visualize` from the `undo-tree` package. Looks like it happens when the cursor jumps to a new window and the cursor isn't allowed to move forward.

```elisp
(defun beacon--dec ()
  "Decrease the beacon brightness by one."
  (pcase (beacon--ov-at-point)
    (`nil (beacon--vanish))
    ((and o (let c (overlay-get o 'beacon-colors)) (guard c))
     (beacon--ov-put-after-string o (cdr c)))
    (o
     (delete-overlay o)
     (save-excursion
       (while (progn (forward-char 1)
                     (setq o (beacon--ov-at-point)))
         (let ((colors (overlay-get o 'beacon-colors)))
           (if (not colors)
               (move-overlay o (1- (point)) (point))
             (forward-char -1)
             (beacon--colored-overlay (pop colors))
             (beacon--ov-put-after-string o colors)
             (forward-char 1))))))))
```

When I remove the `(forward-char 1)` at the end, the error disappears. Didn't look into the best way to fix it but with this hopefully you'll be able to reproduce it.

**Comment by Malabarba** [comment]
Thanks Okke, that helped!

**Comment by otijhuis** [comment]
No problem. Thanks for the quick fix and for another great package!
