### ISSUE TITLE
Blinking beacon displaces text

### ISSUE THREAD

**Issue by eigengrau** [Malabarba/beacon#44]
I recently upgraded from `beacon-20160206.917` to `beacon-20160321.551`. I’ve noticed that now, at least in mu4e-headers-mode, the blinking beacon will displace text in the first line of the buffer.

![screenshot](https://ptpb.pw/u7eQ.png)

This displacement is «animated», i.e., as the beacon blink shrinks away, the displaced text will gradually slide back into its intended position.

This happens only when the buffer is initially constructed. Once it’s open, doing `M-x beacon-blink` will blink the beacon without triggering this effect.

So far I’ve only observed this in the mu4e headers list.

**Comment by Malabarba** [comment]
Yes, I've noticed this occasionally too. It happens because the beacon somehow blinks before the text is inserted, and then the text is inserted after the overlay. 

I haven't had time to look further into it, but if anyone knows why the overlay is blinking before the text is inserted it would help a lot.

**Comment by Malabarba** [comment]
I've pushed a change that might fix this issue. Let me know if it works for you.

**Comment by eigengrau** [comment]
Great, this resolves the displacement issue for me. Thank you kindly. I don’t see an initial beacon blink anymore when a buffer is created in the affected mode, either, but at least in this mode that’s no loss.

Thanks for making beacon!
